require "pp"

TEMPLATE = <<EOF
// Copyright (c) %s, R.I. Pienaar and the Choria Project contributors
//
// SPDX-License-Identifier: Apache-2.0

EOF

Dir.glob("*/**/*.go").each do |file|
  ["aaa_signerclient", "choria_provisionclient", "choria_registryclient", "choria_utilclient", "rpcutilclient", "scoutclient"].each do |ign|
    next if file =~ /#{ign}/
  end

  earliest = `git log --full-history --follow --reverse --date='format:%Y' --format='%ad' #{file} | head -n 1`.chomp
  if earliest == "2021"
    dates = "2021"
  else
    dates = "%s-2021" % [earliest]
  end
  copyright = TEMPLATE % [dates]
  content = File.read(file)

  if content.include?("SPDX-License-Identifier") || content.include?("Code generated by MockGen")
    puts "Skipping %s" % file
    next
  end

  puts "%s: %s" % [earliest, file]

  File.open(file, "w") do |out|
    out.puts copyright
    out.puts content
  end
end
