// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/choria-io/go-choria/inter (interfaces: SecurityProvider)

// Package imock is a generated GoMock package.
package imock

import (
	context "context"
	tls "crypto/tls"
	x509 "crypto/x509"
	pem "encoding/pem"
	http "net/http"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockSecurityProvider is a mock of SecurityProvider interface.
type MockSecurityProvider struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityProviderMockRecorder
}

// MockSecurityProviderMockRecorder is the mock recorder for MockSecurityProvider.
type MockSecurityProviderMockRecorder struct {
	mock *MockSecurityProvider
}

// NewMockSecurityProvider creates a new mock instance.
func NewMockSecurityProvider(ctrl *gomock.Controller) *MockSecurityProvider {
	mock := &MockSecurityProvider{ctrl: ctrl}
	mock.recorder = &MockSecurityProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityProvider) EXPECT() *MockSecurityProviderMockRecorder {
	return m.recorder
}

// CachePublicData mocks base method.
func (m *MockSecurityProvider) CachePublicData(arg0 []byte, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CachePublicData", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CachePublicData indicates an expected call of CachePublicData.
func (mr *MockSecurityProviderMockRecorder) CachePublicData(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CachePublicData", reflect.TypeOf((*MockSecurityProvider)(nil).CachePublicData), arg0, arg1)
}

// CachedPublicData mocks base method.
func (m *MockSecurityProvider) CachedPublicData(arg0 string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CachedPublicData", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CachedPublicData indicates an expected call of CachedPublicData.
func (mr *MockSecurityProviderMockRecorder) CachedPublicData(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CachedPublicData", reflect.TypeOf((*MockSecurityProvider)(nil).CachedPublicData), arg0)
}

// CallerIdentity mocks base method.
func (m *MockSecurityProvider) CallerIdentity(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallerIdentity", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CallerIdentity indicates an expected call of CallerIdentity.
func (mr *MockSecurityProviderMockRecorder) CallerIdentity(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallerIdentity", reflect.TypeOf((*MockSecurityProvider)(nil).CallerIdentity), arg0)
}

// CallerName mocks base method.
func (m *MockSecurityProvider) CallerName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallerName")
	ret0, _ := ret[0].(string)
	return ret0
}

// CallerName indicates an expected call of CallerName.
func (mr *MockSecurityProviderMockRecorder) CallerName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallerName", reflect.TypeOf((*MockSecurityProvider)(nil).CallerName))
}

// ChecksumBytes mocks base method.
func (m *MockSecurityProvider) ChecksumBytes(arg0 []byte) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChecksumBytes", arg0)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// ChecksumBytes indicates an expected call of ChecksumBytes.
func (mr *MockSecurityProviderMockRecorder) ChecksumBytes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChecksumBytes", reflect.TypeOf((*MockSecurityProvider)(nil).ChecksumBytes), arg0)
}

// ChecksumString mocks base method.
func (m *MockSecurityProvider) ChecksumString(arg0 string) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChecksumString", arg0)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// ChecksumString indicates an expected call of ChecksumString.
func (mr *MockSecurityProviderMockRecorder) ChecksumString(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChecksumString", reflect.TypeOf((*MockSecurityProvider)(nil).ChecksumString), arg0)
}

// ClientTLSConfig mocks base method.
func (m *MockSecurityProvider) ClientTLSConfig() (*tls.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientTLSConfig")
	ret0, _ := ret[0].(*tls.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClientTLSConfig indicates an expected call of ClientTLSConfig.
func (mr *MockSecurityProviderMockRecorder) ClientTLSConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientTLSConfig", reflect.TypeOf((*MockSecurityProvider)(nil).ClientTLSConfig))
}

// Enroll mocks base method.
func (m *MockSecurityProvider) Enroll(arg0 context.Context, arg1 time.Duration, arg2 func(string, int)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enroll", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enroll indicates an expected call of Enroll.
func (mr *MockSecurityProviderMockRecorder) Enroll(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enroll", reflect.TypeOf((*MockSecurityProvider)(nil).Enroll), arg0, arg1, arg2)
}

// HTTPClient mocks base method.
func (m *MockSecurityProvider) HTTPClient(arg0 bool) (*http.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HTTPClient", arg0)
	ret0, _ := ret[0].(*http.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HTTPClient indicates an expected call of HTTPClient.
func (mr *MockSecurityProviderMockRecorder) HTTPClient(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HTTPClient", reflect.TypeOf((*MockSecurityProvider)(nil).HTTPClient), arg0)
}

// Identity mocks base method.
func (m *MockSecurityProvider) Identity() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Identity")
	ret0, _ := ret[0].(string)
	return ret0
}

// Identity indicates an expected call of Identity.
func (mr *MockSecurityProviderMockRecorder) Identity() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Identity", reflect.TypeOf((*MockSecurityProvider)(nil).Identity))
}

// IsRemoteSigning mocks base method.
func (m *MockSecurityProvider) IsRemoteSigning() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRemoteSigning")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRemoteSigning indicates an expected call of IsRemoteSigning.
func (mr *MockSecurityProviderMockRecorder) IsRemoteSigning() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRemoteSigning", reflect.TypeOf((*MockSecurityProvider)(nil).IsRemoteSigning))
}

// PrivilegedVerifyByteSignature mocks base method.
func (m *MockSecurityProvider) PrivilegedVerifyByteSignature(arg0, arg1 []byte, arg2 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrivilegedVerifyByteSignature", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	return ret0
}

// PrivilegedVerifyByteSignature indicates an expected call of PrivilegedVerifyByteSignature.
func (mr *MockSecurityProviderMockRecorder) PrivilegedVerifyByteSignature(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrivilegedVerifyByteSignature", reflect.TypeOf((*MockSecurityProvider)(nil).PrivilegedVerifyByteSignature), arg0, arg1, arg2)
}

// PrivilegedVerifyStringSignature mocks base method.
func (m *MockSecurityProvider) PrivilegedVerifyStringSignature(arg0 string, arg1 []byte, arg2 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrivilegedVerifyStringSignature", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	return ret0
}

// PrivilegedVerifyStringSignature indicates an expected call of PrivilegedVerifyStringSignature.
func (mr *MockSecurityProviderMockRecorder) PrivilegedVerifyStringSignature(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrivilegedVerifyStringSignature", reflect.TypeOf((*MockSecurityProvider)(nil).PrivilegedVerifyStringSignature), arg0, arg1, arg2)
}

// Provider mocks base method.
func (m *MockSecurityProvider) Provider() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Provider")
	ret0, _ := ret[0].(string)
	return ret0
}

// Provider indicates an expected call of Provider.
func (mr *MockSecurityProviderMockRecorder) Provider() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Provider", reflect.TypeOf((*MockSecurityProvider)(nil).Provider))
}

// PublicCert mocks base method.
func (m *MockSecurityProvider) PublicCert() (*x509.Certificate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicCert")
	ret0, _ := ret[0].(*x509.Certificate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublicCert indicates an expected call of PublicCert.
func (mr *MockSecurityProviderMockRecorder) PublicCert() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicCert", reflect.TypeOf((*MockSecurityProvider)(nil).PublicCert))
}

// PublicCertPem mocks base method.
func (m *MockSecurityProvider) PublicCertPem() (*pem.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicCertPem")
	ret0, _ := ret[0].(*pem.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublicCertPem indicates an expected call of PublicCertPem.
func (mr *MockSecurityProviderMockRecorder) PublicCertPem() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicCertPem", reflect.TypeOf((*MockSecurityProvider)(nil).PublicCertPem))
}

// PublicCertTXT mocks base method.
func (m *MockSecurityProvider) PublicCertBytes() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicCertBytes")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublicCertTXT indicates an expected call of PublicCertTXT.
func (mr *MockSecurityProviderMockRecorder) PublicCertTXT() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicCertBytes", reflect.TypeOf((*MockSecurityProvider)(nil).PublicCertBytes))
}

// RemoteSignRequest mocks base method.
func (m *MockSecurityProvider) RemoteSignRequest(arg0 context.Context, arg1 []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoteSignRequest", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoteSignRequest indicates an expected call of RemoteSignRequest.
func (mr *MockSecurityProviderMockRecorder) RemoteSignRequest(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoteSignRequest", reflect.TypeOf((*MockSecurityProvider)(nil).RemoteSignRequest), arg0, arg1)
}

// SSLContext mocks base method.
func (m *MockSecurityProvider) SSLContext() (*http.Transport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SSLContext")
	ret0, _ := ret[0].(*http.Transport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SSLContext indicates an expected call of SSLContext.
func (mr *MockSecurityProviderMockRecorder) SSLContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SSLContext", reflect.TypeOf((*MockSecurityProvider)(nil).SSLContext))
}

// SignBytes mocks base method.
func (m *MockSecurityProvider) SignBytes(arg0 []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignBytes", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignBytes indicates an expected call of SignBytes.
func (mr *MockSecurityProviderMockRecorder) SignBytes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignBytes", reflect.TypeOf((*MockSecurityProvider)(nil).SignBytes), arg0)
}

// SignString mocks base method.
func (m *MockSecurityProvider) SignString(arg0 string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignString", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignString indicates an expected call of SignString.
func (mr *MockSecurityProviderMockRecorder) SignString(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignString", reflect.TypeOf((*MockSecurityProvider)(nil).SignString), arg0)
}

// TLSConfig mocks base method.
func (m *MockSecurityProvider) TLSConfig() (*tls.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TLSConfig")
	ret0, _ := ret[0].(*tls.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TLSConfig indicates an expected call of TLSConfig.
func (mr *MockSecurityProviderMockRecorder) TLSConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TLSConfig", reflect.TypeOf((*MockSecurityProvider)(nil).TLSConfig))
}

// Validate mocks base method.
func (m *MockSecurityProvider) Validate() ([]string, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockSecurityProviderMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockSecurityProvider)(nil).Validate))
}

// VerifyByteSignature mocks base method.
func (m *MockSecurityProvider) VerifyByteSignature(arg0, arg1 []byte, arg2 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyByteSignature", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	return ret0
}

// VerifyByteSignature indicates an expected call of VerifyByteSignature.
func (mr *MockSecurityProviderMockRecorder) VerifyByteSignature(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyByteSignature", reflect.TypeOf((*MockSecurityProvider)(nil).VerifyByteSignature), arg0, arg1, arg2)
}

// VerifyCertificate mocks base method.
func (m *MockSecurityProvider) VerifyCertificate(arg0 []byte, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyCertificate", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyCertificate indicates an expected call of VerifyCertificate.
func (mr *MockSecurityProviderMockRecorder) VerifyCertificate(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyCertificate", reflect.TypeOf((*MockSecurityProvider)(nil).VerifyCertificate), arg0, arg1)
}

// VerifyStringSignature mocks base method.
func (m *MockSecurityProvider) VerifyStringSignature(arg0 string, arg1 []byte, arg2 string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyStringSignature", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	return ret0
}

// VerifyStringSignature indicates an expected call of VerifyStringSignature.
func (mr *MockSecurityProviderMockRecorder) VerifyStringSignature(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyStringSignature", reflect.TypeOf((*MockSecurityProvider)(nil).VerifyStringSignature), arg0, arg1, arg2)
}
