// Code generated by MockGen. DO NOT EDIT.
// Source: network.go
//
// Generated by this command:
//
//	mockgen -write_generate_directive -source network.go -destination network_mock_test.go -package network
//

// Package network is a generated GoMock package.
package network

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -write_generate_directive -source network.go -destination network_mock_test.go -package network

// MockBuildInfoProvider is a mock of BuildInfoProvider interface.
type MockBuildInfoProvider struct {
	ctrl     *gomock.Controller
	recorder *MockBuildInfoProviderMockRecorder
	isgomock struct{}
}

// MockBuildInfoProviderMockRecorder is the mock recorder for MockBuildInfoProvider.
type MockBuildInfoProviderMockRecorder struct {
	mock *MockBuildInfoProvider
}

// NewMockBuildInfoProvider creates a new mock instance.
func NewMockBuildInfoProvider(ctrl *gomock.Controller) *MockBuildInfoProvider {
	mock := &MockBuildInfoProvider{ctrl: ctrl}
	mock.recorder = &MockBuildInfoProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildInfoProvider) EXPECT() *MockBuildInfoProviderMockRecorder {
	return m.recorder
}

// MaxBrokerClients mocks base method.
func (m *MockBuildInfoProvider) MaxBrokerClients() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxBrokerClients")
	ret0, _ := ret[0].(int)
	return ret0
}

// MaxBrokerClients indicates an expected call of MaxBrokerClients.
func (mr *MockBuildInfoProviderMockRecorder) MaxBrokerClients() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxBrokerClients", reflect.TypeOf((*MockBuildInfoProvider)(nil).MaxBrokerClients))
}
