// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/choria-io/go-choria/server (interfaces: AgentManager)

// Package external is a generated GoMock package.
package ruby

import (
	context "context"
	reflect "reflect"

	inter "github.com/choria-io/go-choria/inter"
	agents "github.com/choria-io/go-choria/server/agents"
	gomock "github.com/golang/mock/gomock"
	logrus "github.com/sirupsen/logrus"
)

// MockAgentManager is a mock of AgentManager interface.
type MockAgentManager struct {
	ctrl     *gomock.Controller
	recorder *MockAgentManagerMockRecorder
}

// MockAgentManagerMockRecorder is the mock recorder for MockAgentManager.
type MockAgentManagerMockRecorder struct {
	mock *MockAgentManager
}

// NewMockAgentManager creates a new mock instance.
func NewMockAgentManager(ctrl *gomock.Controller) *MockAgentManager {
	mock := &MockAgentManager{ctrl: ctrl}
	mock.recorder = &MockAgentManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentManager) EXPECT() *MockAgentManagerMockRecorder {
	return m.recorder
}

// Choria mocks base method.
func (m *MockAgentManager) Choria() inter.Framework {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Choria")
	ret0, _ := ret[0].(inter.Framework)
	return ret0
}

// Choria indicates an expected call of Choria.
func (mr *MockAgentManagerMockRecorder) Choria() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Choria", reflect.TypeOf((*MockAgentManager)(nil).Choria))
}

// Logger mocks base method.
func (m *MockAgentManager) Logger() *logrus.Entry {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(*logrus.Entry)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockAgentManagerMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockAgentManager)(nil).Logger))
}

// RegisterAgent mocks base method.
func (m *MockAgentManager) RegisterAgent(arg0 context.Context, arg1 string, arg2 agents.Agent, arg3 inter.AgentConnector) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterAgent", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterAgent indicates an expected call of RegisterAgent.
func (mr *MockAgentManagerMockRecorder) RegisterAgent(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterAgent", reflect.TypeOf((*MockAgentManager)(nil).RegisterAgent), arg0, arg1, arg2, arg3)
}

// ReplaceAgent mocks base method.
func (m *MockAgentManager) ReplaceAgent(arg0 string, arg1 agents.Agent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceAgent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceAgent indicates an expected call of ReplaceAgent.
func (mr *MockAgentManagerMockRecorder) ReplaceAgent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceAgent", reflect.TypeOf((*MockAgentManager)(nil).ReplaceAgent), arg0, arg1)
}

// UnregisterAgent mocks base method.
func (m *MockAgentManager) UnregisterAgent(arg0 string, arg1 inter.AgentConnector) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnregisterAgent", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnregisterAgent indicates an expected call of UnregisterAgent.
func (mr *MockAgentManagerMockRecorder) UnregisterAgent(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterAgent", reflect.TypeOf((*MockAgentManager)(nil).UnregisterAgent), arg0, arg1)
}
