#!/bin/sh

action="$1"

if [ "$action" = configure ]; then
	old_version="$2"

	if [ -z "$old_version" ]; then
		systemctl enable choria-server.service
	else
		systemctl try-restart choria-broker.service choria-server.service
	fi
fi
