// Code generated by MockGen. DO NOT EDIT.
// Source: mutators.go
//
// Generated by this command:
//
//	mockgen -write_generate_directive -source mutators.go -package config -destination mutator_mock_test.go
//

// Package config is a generated GoMock package.
package config

import (
	reflect "reflect"

	logrus "github.com/sirupsen/logrus"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -write_generate_directive -source mutators.go -package config -destination mutator_mock_test.go

// MockMutator is a mock of Mutator interface.
type MockMutator struct {
	ctrl     *gomock.Controller
	recorder *MockMutatorMockRecorder
	isgomock struct{}
}

// MockMutatorMockRecorder is the mock recorder for MockMutator.
type MockMutatorMockRecorder struct {
	mock *MockMutator
}

// NewMockMutator creates a new mock instance.
func NewMockMutator(ctrl *gomock.Controller) *MockMutator {
	mock := &MockMutator{ctrl: ctrl}
	mock.recorder = &MockMutatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMutator) EXPECT() *MockMutatorMockRecorder {
	return m.recorder
}

// Mutate mocks base method.
func (m *MockMutator) Mutate(arg0 *Config, arg1 *logrus.Entry) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Mutate", arg0, arg1)
}

// Mutate indicates an expected call of Mutate.
func (mr *MockMutatorMockRecorder) Mutate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mutate", reflect.TypeOf((*MockMutator)(nil).Mutate), arg0, arg1)
}
