name: Choria Repository Installation Check
on:
  workflow_dispatch: {}
  schedule:
    - cron: "40 5 * * *"

permissions:
  contents: read

jobs:
  el_64:
    runs-on: ubuntu-latest
    steps:
      - name: EL Installation Tests
        shell: bash
        run: docker run --entrypoint=/bin/install-choria.sh registry.choria.io/choria/packager:el-go1.24

  deb_64:
    runs-on: ubuntu-latest
    steps:
      - name: Debian Installation Tests
        shell: bash
        run: docker run --entrypoint=/bin/install-choria.sh registry.choria.io/choria/packager:deb-go1.24
