name: Choria Repository Installation Check
on:
  workflow_dispatch: {}
  schedule:
    - cron: "40 5 * * *"

jobs:
  el7_64:
    runs-on: ubuntu-latest
    steps:
      - name: EL7 Installation Tests
        shell: bash
        run: docker run --entrypoint=/bin/install-choria.sh registry.choria.io/choria/packager:el7-go1.21

  el8_64:
    runs-on: ubuntu-latest
    steps:
      - name: EL8 Installation Tests
        shell: bash
        run: docker run --entrypoint=/bin/install-choria.sh registry.choria.io/choria/packager:el8-go1.21

  el9_64:
    runs-on: ubuntu-latest
    steps:
      - name: EL9 Installation Tests
        shell: bash
        run: docker run --entrypoint=/bin/install-choria.sh registry.choria.io/choria/packager:el9-go1.21

  bionic_64:
    runs-on: ubuntu-latest
    steps:
      - name: Bionic Installation Tests
        shell: bash
        run: docker run --entrypoint=/bin/install-choria.sh registry.choria.io/choria/packager:bionic-go1.21

  focal_64:
    runs-on: ubuntu-latest
    steps:
      - name: Focal Installation Tests
        shell: bash
        run: docker run --entrypoint=/bin/install-choria.sh registry.choria.io/choria/packager:focal-go1.21

  buster_64:
    runs-on: ubuntu-latest
    steps:
      - name: Buster Installation Tests
        shell: bash
        run: docker run --entrypoint=/bin/install-choria.sh registry.choria.io/choria/packager:buster-go1.21

  bullseye_64:
    runs-on: ubuntu-latest
    steps:
      - name: Bullseye Installation Tests
        shell: bash
        run: docker run --entrypoint=/bin/install-choria.sh registry.choria.io/choria/packager:bullseye-go1.21
