name: Choria Repository Installation Check
on:
  workflow_dispatch: {}
  schedule:
    - cron: "40 5 * * *"

jobs:
  el8_64:
    runs-on: ubuntu-latest
    steps:
      - name: EL8 Installation Tests
        shell: bash
        run: docker run --entrypoint=/bin/install-choria.sh registry.choria.io/choria/packager:el8-go1.24

  el9_64:
    runs-on: ubuntu-latest
    steps:
      - name: EL9 Installation Tests
        shell: bash
        run: docker run --entrypoint=/bin/install-choria.sh registry.choria.io/choria/packager:el9-go1.24

  bionic_64:
    runs-on: ubuntu-latest
    steps:
      - name: Bionic Installation Tests
        shell: bash
        run: docker run --entrypoint=/bin/install-choria.sh registry.choria.io/choria/packager:bionic-go1.24

  focal_64:
    runs-on: ubuntu-latest
    steps:
      - name: Focal Installation Tests
        shell: bash
        run: docker run --entrypoint=/bin/install-choria.sh registry.choria.io/choria/packager:focal-go1.24

  noble_64:
    runs-on: ubuntu-latest
    steps:
      - name: Noble Installation Tests
        shell: bash
        run: docker run --entrypoint=/bin/install-choria.sh registry.choria.io/choria/packager:noble-go1.24

  bullseye_64:
    runs-on: ubuntu-latest
    steps:
      - name: Bullseye Installation Tests
        shell: bash
        run: docker run --entrypoint=/bin/install-choria.sh registry.choria.io/choria/packager:bullseye-go1.24

  bookworm_64:
    runs-on: ubuntu-latest
    steps:
      - name: Bookworm Installation Tests
        shell: bash
        run: docker run --entrypoint=/bin/install-choria.sh registry.choria.io/choria/packager:bookworm-go1.24
