name: Integration Tests
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: ["1.24"]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go}}

      - name: Integration Tests
        shell: bash
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo
          ginkgo --keep-going -vet=off -r integration
