name: Unit Tests
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: ["1.24", "1.25"]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go}}
          check-latest: true

      - name: Lint and Test
        uses: choria-io/actions/lint_and_test/go@main
        with:
          ginkgo: "v2"
